version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: npm run build
  lint:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: npm run lintall
  test:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run: npm run test