version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout
      - run: npm run build
  lint:
    <<: *defaults 
    steps:
      - checkout
      - run: npm run lintall
  test:
    <<: *defaults 
    steps:
      - checkout
      - run: npm run test