version: 2

defaults: &defaults
  docker:
    - image: circleci/node:jessie-browsers

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npm run lintall
      - run: npm run test